### ISSUE TITLE
Vite always imports cjs

### ISSUE THREAD

**Issue by timrittgers** [pengzhanbo/vite-plugin-image-placeholder#1]
I’m having trouble getting vite to correctly pull the right asset from your package. No matter how I configure it, vite always pulls the cjs file instead of the js module file, which then causes my storybook build to break with an error due to the require statements. I’ve tried to use resolve alias configuration to force the path to the js file. The only way I can get the code to render is by removing the cjs declarations in your package.json file after I’ve installed the package, then it works great. Any suggestions?

Also, I’ve noticed that the placeholder images don’t seem to work when the site is output as a static web app via the build-storybook command - is this a known limitation?

**Comment by pengzhanbo** [comment]
Do you have the `type` field in your project's `package.json` set to `module`?
``` json
{
  "type": "module"
}
```
Then, are you importing using `import` in your project, like this:
``` ts
import plugin from 'vite-plugin-image-placeholder'
```
If your project is in TypeScript, do you have the following configuration in your `tsconfig.json`:
``` ts
{
    "module": "ESNext",
    "moduleResolution": "Node",
}
```
> If using `create-vite`, the default configuration is in `tsconfig.node.json`

`Vite` loads and parses `vite.config.{js,ts}` based on these settings. The imported file type is an `es module`.
The plugin also configures the `exports` field according to the `node module` specification:
```json
{
  "exports": {
    ".": {
      "require": "./dist/index.cjs",
      "import": "./dist/index.js"
    }
  },
  "main": "dist/index.cjs",
  "module": "dist/index.js",
  "types": "dist/index.d.ts",
}
```
It is compatible with `cjs/esm` imports.
In `storybook`, you need to use `@storybook/builder-vite` as the `builder`. It will load your project's `vite.config.ts`, and if it matches the documentation, then import placeholder can be resolved.

**Comment by timrittgers** [comment]
Can the package work with statically generated storybook sites?
